[package]
name = "wallpapers"
version = "0.1.0"
edition = "2021"
description = "Awused's personal image and manga viewer"
readme = "README.md"
license = "MIT"
keywords = ["wallpapers", "waifu2x"]
homepage = "https://github.com/awused/wallpapers"
repository = "https://github.com/awused/wallpapers"
links = "X11, Xrandr"


[dependencies]
awconf = { git = "https://github.com/awused/awconf" }
aw-shuffle = { git = "https://github.com/awused/aw-shuffle", features = [ "rocks" ] }
aw-upscale = { git = "https://github.com/awused/aw-upscale" }
clap = { version = "4.3.23", features = ["derive"] }
crossbeam-utils = "0.8.16"
dialoguer = { version = "0.10.4", default-features = false, features = [ "history" ] }
image = { version = "0.24.7", default-features = false, features = [ "jpeg", "png", "bmp" ] }
lru = { version = "0.11.0", default-features = false }
num_cpus = "1.16.0"
ocl = { version = "0.19.4", optional = true }
once_cell = "1.18.0"
rayon = "1.7.0"
regex = "1.9.3"
serde = { version = "1.0.185", default-features = false, features = [ "derive" ] }
signal-hook = { version = "0.3.17", default-features = false }
tempfile = "3.8.0"
tokio = { version = "1.32.0", features = [ "macros", "process", "rt", "sync", "time" ] }
toml = "0.7.6"
walkdir = "2.3.3"


[target.'cfg(unix)'.dependencies]
libc = "0.2.147"
futures = "0.3.28"
tikv-jemallocator = { version = "0.5.4", features = [ "background_threads" ] }
x11 = "2.21.0"

[target.'cfg(windows)'.dependencies]
widestring = "1.0.2"

[target.'cfg(windows)'.dependencies.windows]
version = "0.51.1"
features = [
  "Win32_Foundation",
  "Win32_System_Com",
  "Win32_UI_Shell"
]

[features]
default = ["opencl"]
windows-quiet = []
opencl = ["dep:ocl"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
overflow-checks = false
