[package]
name = "wallpapers"
version = "0.1.0"
edition = "2021"
description = "Awused's personal image and manga viewer"
readme = "README.md"
license = "MIT"
keywords = ["wallpapers", "waifu2x"]
homepage = "https://github.com/awused/wallpapers"
repository = "https://github.com/awused/wallpapers"
links = "X11, Xrandr"


[dependencies]
awconf = { git = "https://github.com/awused/awconf" }
aw-shuffle = { git = "https://github.com/awused/aw-shuffle", features = [ "rocks" ] }
aw-upscale = { git = "https://github.com/awused/aw-upscale" }
clap = { version = "4.1.8", features = ["derive"] }
crossbeam-utils = "0.8.15"
dialoguer = { version = "0.10.3", default-features = false, features = [ "history" ] }
image = { version = "0.24.5", default-features = false, features = [ "jpeg", "png", "bmp" ] }
lru = { version = "0.10.0", default-features = false }
num_cpus = "1.15.0"
ocl = { version = "0.19.4", optional = true }
once_cell = "1.17.1"
rayon = "1.7.0"
regex = "1.7.1"
serde = { version = "1.0.154", default-features = false, features = [ "derive" ] }
signal-hook = { version = "0.3.15", default-features = false }
tempfile = "3.4.0"
tokio = { version = "1.26.0", features = [ "macros", "process", "rt", "sync", "time" ] }
toml = "0.7.2"
walkdir = "2.3.2"


[target.'cfg(unix)'.dependencies]
libc = "0.2.140"
futures = "0.3.26"
tikv-jemallocator = { version = "0.5.0", features = [ "background_threads" ] }
x11 = "2.21.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [ "std", "shobjidl_core" ] }
widestring = "1.0.2"


[features]
default = ["opencl"]
windows-quiet = []
opencl = ["dep:ocl"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
overflow-checks = false
