[package]
name = "wallpapers"
version = "0.1.0"
edition = "2021"
description = "Awused's personal image and manga viewer"
readme = "README.md"
license = "MIT"
keywords = ["wallpapers", "waifu2x"]
homepage = "https://github.com/awused/wallpapers"
repository = "https://github.com/awused/wallpapers"
links = "X11, Xrandr"


[dependencies]
awconf = { git = "https://github.com/awused/awconf" }
aw-shuffle = { git = "https://github.com/awused/aw-shuffle", features = [ "rocks" ] }
aw-upscale = { git = "https://github.com/awused/aw-upscale" }
clap = { version = "3.2.16", features = ["derive"] }
crossbeam-utils = "0.8.11"
dialoguer = { version = "0.10.2", default-features = false, features = [ "history" ] }
image = { version = "0.24.3", default-features = false, features = [ "jpeg", "png", "bmp" ] }
lru = { version = "0.7.8", default-features = false }
num_cpus = "1.13.1"
ocl = { version = "0.19.3", optional = true }
once_cell = "1.13.0"
rayon = "1.5.3"
regex = "1.6.0"
serde = { version = "1.0.142", default-features = false, features = [ "derive" ] }
signal-hook = { version = "0.3.14", default-features = false }
tempfile = "3.3.0"
tokio = { version = "1.20.1", features = [ "macros", "process", "rt", "sync", "time" ] }
toml = "0.5.9"
walkdir = "2.3.2"


[target.'cfg(unix)'.dependencies]
libc = "0.2.127"
futures = "0.3.21"
tikv-jemallocator = { version = "0.5.0", features = [ "background_threads" ] }
x11 = "2.19.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [ "std", "shobjidl_core" ] }
widestring = "1.0.2"


[features]
default = ["opencl"]
windows-quiet = []
opencl = ["dep:ocl"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
overflow-checks = false
