[package]
name = "wallpapers"
version = "0.1.0"
edition = "2021"
description = "Awused's personal image and manga viewer"
readme = "README.md"
license = "MIT"
keywords = ["wallpapers", "waifu2x"]
homepage = "https://github.com/awused/wallpapers"
repository = "https://github.com/awused/wallpapers"
links = "X11, Xinerama"


[dependencies]
awconf = { git = "https://github.com/awused/awconf" }
aw-shuffle = { git = "https://github.com/awused/aw-shuffle", features = [ "rocks" ] }
aw-upscale = { git = "https://github.com/awused/aw-upscale" }
clap = { version = "3.2.12", features = ["derive"] }
crossbeam-utils = "0.8.10"
dialoguer = { version = "0.10.1", default-features = false, features = [ "history" ] }
image = { version = "0.24.2", default-features = false, features = [ "jpeg", "png", "bmp" ] }
num_cpus = "1.13.1"
num-traits = "0.2.15"
once_cell = "1.13.0"
rayon = "1.5.3"
serde = { version = "1.0.139", default-features = false, features = [ "derive" ] }
signal-hook = { version = "0.3.14", default-features = false }
tempfile = "3.3.0"
tokio = { version = "1.20.0", features = [ "macros", "process", "rt", "sync", "time" ] }
toml = "0.5.9"
walkdir = "2.3.2"

[target.'cfg(unix)'.dependencies]
x11 = "2.19.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [ "std", "shobjidl_core" ] }
widestring = "1.0.2"

[features]
windows-quiet = []

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
overflow-checks = false
